name: tfm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0
  - _openmp_mutex=4.5
  - affine=2.4.0
  - anyio=4.10.0
  - aom=3.9.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - branca=0.8.1
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - click=8.1.8
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.0
  - cpython=3.9.23
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.3
  - folium=0.20.0
  - fonttools=4.59.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - freexl=2.0.0
  - geoalchemy2=0.17.1
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.13.0
  - geotiff=1.7.4
  - greenlet=3.2.4
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - ipykernel=6.30.1
  - ipython=8.18.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.2.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lark=1.2.2
  - lcms2=2.17
  - lerc=4.0.0
  - libarchive=3.7.7
  - libavif16=1.3.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcurl=8.17.0
  - libde265=1.0.15
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgdal-core=3.10.0
  - libgomp=15.2.0
  - libheif=1.18.2
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libkml=1.3.0
  - liblapack=3.11.0
  - libpng=1.6.53
  - libpq=17.7
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.7
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.8.1
  - markupsafe=3.0.2
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - minizip=4.0.6
  - mistune=3.1.3
  - mkl=2025.3.0
  - munkres=1.1.4
  - narwhals=2.1.2
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook-shim=0.2.4
  - numpy=2.0.2
  - openjpeg=2.5.3
  - openssl=3.6.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.1
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.3
  - platformdirs=4.3.8
  - plotly=6.3.0
  - proj=9.5.1
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - psycopg2=2.9.10
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyogrio=0.10.0
  - pyparsing=3.2.3
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.9.25
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.2
  - pyzmq=27.0.2
  - qhull=2020.2
  - rasterio=1.4.3
  - rav1e=0.7.1
  - referencing=0.36.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.27.0
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shapely=2.0.7
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - snuggs=1.4.7
  - soupsieve=2.7
  - sqlalchemy=2.0.43
  - sqlite=3.51.0
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - svt-av1=3.1.2
  - tbb=2022.3.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.2
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250809
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - typing_utils=0.1.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - x265=3.5
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.11.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
prefix: C:\Users\mosqu\.conda\envs\tfm_env
